# -*- coding: utf-8 -*-
"""Copy of ml_homonimo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18JijF8dSxbo5-kXXRnHLMJ8TfzWuFl_o
"""

import pandas as pd
import numpy as np
import time
import math
from tqdm.notebook import tqdm
import os
import xgboost as xgb
import shap

import lightgbm as lgb
from lightgbm import LGBMRanker

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

import matplotlib.pyplot as plt

path_results = "results.txt"

FEATURE_COLS = [
    "cos_endereco",
    "missing_cos_endereco",
    "cos_profissao",
    "missing_cos_profissao",
    "age_score",
    "missing_age_score",
    "is_child",
    "is_spouse_partner",
    "is_other_relative"
]

TARGET_COL = "label"
GROUP_COL = "qid"

def load_local_data(split):
    df_train = pd.read_csv(f"fold{split}_train.csv")
    df_val = pd.read_csv(f"fold{split}_val.csv")
    df_test = pd.read_csv(f"fold{split}_test.csv")

    return df_train, df_val, df_test

def train_reg_log_classifier (df_train, df_valid, features):
    cols_to_fill = [
        "age_score",
        "address_score_ml_base",
        "prof_score_ml_base",
        "addr_lev_logradouro",
        "addr_ext_cidade",
        "addr_ext_estado",
    ]

    df_train = df_train.sample(frac=1, random_state=42).reset_index(drop=True)

    X_train = df_train[features].fillna(0)
    Y_train = df_train[TARGET_COL]

    X_valid = df_valid[features].fillna(0)
    Y_valid =  df_valid[TARGET_COL]

    scaler = StandardScaler()

    n_pos = (Y_train == 1).sum()
    n_neg = (Y_train == 0).sum()

    class_weight = {
        0: 1.0,
        1: n_neg / n_pos
    }

    model = LogisticRegression(
        penalty="l2",
        solver="lbfgs",
        max_iter=3000,
        class_weight=class_weight,
        n_jobs=-1
    )

    pipeline = Pipeline([
        ("scaler", scaler),
        ("clf", model)
    ])

    pipeline.fit(X_train, Y_train)

    y_valid_proba = pipeline.predict_proba(X_valid)[:, 1]
    auc = roc_auc_score(Y_valid, y_valid_proba)

    print("Validation AUC:", auc)
    # adicionar ao arquivo de resultados
    with open(path_results, "a") as f:
        f.write(f"Logistic Regression - Validation AUC: {auc:.4f}\n")

    return pipeline

def train_xgb_ranker (df_train, df_valid, features):

    df_train = df_train.sort_values(GROUP_COL)
    df_valid = df_valid.sort_values(GROUP_COL)

    X_train = df_train[features].fillna(0)
    Y_train = df_train[TARGET_COL]

    X_valid = df_valid[features].fillna(0)
    Y_valid =  df_valid[TARGET_COL]

    group_train = (
        df_train
        .groupby(GROUP_COL)
        .size()
        .values
    )

    group_valid = (
        df_valid
        .groupby(GROUP_COL)
        .size()
        .values
    )

    model = xgb.XGBRanker(
        objective="rank:ndcg",
        eval_metric="ndcg@10",
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        tree_method="hist",
        random_state=42,
        n_jobs=-1
    )

    model.fit(
        X_train,
        Y_train,
        group=group_train,
        eval_set=[(X_valid, Y_valid)],
        eval_group=[group_valid],
        verbose=20
    )

    return model

def train_lgbm_ranker (df_train, df_valid, features):
    df_train = df_train.sort_values(GROUP_COL)
    df_valid = df_valid.sort_values(GROUP_COL)

    X_train = df_train[features].fillna(0)
    Y_train = df_train[TARGET_COL]

    X_valid = df_valid[features].fillna(0)
    Y_valid =  df_valid[TARGET_COL]

    group_train = df_train.groupby(GROUP_COL).size().tolist()
    group_valid = df_valid.groupby(GROUP_COL).size().tolist()

    model = LGBMRanker(
        objective="lambdarank",
        metric="ndcg",
        n_estimators=300,
        learning_rate=0.05,
        max_depth=-1,
        num_leaves=31,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        n_jobs=-1
    )

    model.fit(
        X_train,
        Y_train,
        group=group_train,
        eval_set=[(X_valid, Y_valid)],
        eval_group=[group_valid],
        eval_at=[1, 5, 10],
        callbacks=[
            lgb.log_evaluation(period=20)
        ]
    )

    return model

def ranking_metrics(df, group_col = "qid", label_col = "label", score_col = "score", ks = (1, 5, 10, 15, 20)):
    df = df.sort_values([group_col, score_col], ascending=[True, False]).copy()
    df["rank"] = df.groupby(group_col)[score_col].rank(ascending=False, method="first")

    pos_ranks = df[df[label_col] == 1].groupby(group_col)["rank"].min()

    results={}
    results["MRR"] = (1 / pos_ranks).mean()
    for k in ks:
        results[f"recall@{k}"] = (pos_ranks <= k).mean()

    return results

def lgbm_explainer (df_test, split, features, model_lgbm):
    print("features", features)
    print("cos_prof", df_test[["cos_profissao", "missing_cos_profissao"]].describe())
    print("teste", df_test[["cos_profissao"]].head(20))
    explainer = shap.TreeExplainer(model_lgbm)

    X = df_test[features].copy()
    shap_values = explainer.shap_values(X)

    importance = np.abs(shap_values).mean(axis=0)

    df_importance = pd.DataFrame({
        "feature": X.columns,
        "importance": importance
    }).sort_values("importance", ascending=False)

    total = df_importance["importance"].sum()

    feature_groups = {
        "address": ["cos_endereco"],
        "age": ["age_score"],
        "profession": ["cos_profissao"],
        "relationship_indicators": [
            "is_child",
            "is_spouse_partner",
            "is_other_relative"
        ]
    }

    group_importance = []
    for group, group_features in feature_groups.items():
        imp = df_importance[
            df_importance["feature"].isin(group_features)
        ]["importance"].sum()

        group_importance.append({
            "group": group,
            "importance": imp
        })

    df_group = pd.DataFrame(group_importance)

    df_group["relative_importance"] = (
        100 * (df_group["importance"] / total)
    )
    output_file = f"results/{split}/lgbm_explainer.csv"
    df_group.to_csv(output_file, index=False)
    df_importance.to_csv(f"results/{split}/lgbm_feature_importance.csv", index=False)

def inferencia_local (model, df_test, feature_cols, group_col="qid"):
    df_test = df_test.copy()
    df_test = df_test.sort_values(group_col).reset_index(drop=True)

    X_test = df_test[feature_cols].fillna(0)

    #classifier
    if hasattr(model, "predict_proba"):
        df_test["score"] = model.predict_proba(X_test)[:,1]
    else:
        df_test["score"] = model.predict(X_test)
    return df_test

def inferencia (label, split, features, model, mode="ranker"):
    _, _, df_test = load_local_data(split)
    df_results = inferencia_local(model, df_test, features, GROUP_COL)
    metricas = ranking_metrics(df_results, group_col=GROUP_COL, label_col=TARGET_COL, score_col="score")
    df_results.to_csv(f"result_{label}_{split}.csv", index=False)
    print(f"Results  {label} - split {split}")
    #adicionar ao arquivo de resultados
    with open(path_results, "a") as f:
        f.write(f"Results Inferencia {label} - split {split}\n")
    for nome, valor in metricas.items():
        print(f"{nome}: {valor:.4f}")
        with open(path_results, "a") as f:
            f.write(f"{nome}: {valor:.4f}\n")

    return df_results, metricas

for k in range(5):
    split = k

    print("Loading data")
    with open(path_results, "a") as f:
        f.write(f"Split {split}\n")
    df_train, df_valid, df_test = load_local_data(split)


    label = "reg_log"
    # features = [
    #     "is_child",
    #     "is_spouse_partner",
    #     "is_other_relative",
    #     "age_score",
    #     "cos_endereco",
    #     "cos_profissao",
    #     "missing_age_score",
    #     "missing_cos_profissao",
    #     "missing_cos_endereco",
    # ]

    # Regressão Logistica
    print("Training model Regressão Logistica")
    reg_log_model = train_reg_log_classifier(df_train, df_valid, FEATURE_COLS)
    print("Inference model Regressão Logistica")
    inferencia (label, split, FEATURE_COLS, reg_log_model, mode="classifier")

    # XGBoost
    label = "xgboost_ranker"
    print("Training model XGBoost")
    xgb_model = train_xgb_ranker(df_train, df_valid, FEATURE_COLS)
    print("Inference model XGBoost")
    inferencia (label, split, FEATURE_COLS, xgb_model, mode="ranker")

    # LGBM
    label = "lgbm_ranker"
    print("Training model LGBM")
    lgbm_model = train_lgbm_ranker(df_train, df_valid, FEATURE_COLS)
    print("Inference model LGBM")
    inferencia (label, split, FEATURE_COLS, lgbm_model, mode="ranker")
    # LGBM Explainer
    print("LGBM Explainer")
    lgbm_explainer(df_test, split, FEATURE_COLS, lgbm_model)

